// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvgyclpnrhsjuqvsghxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Z3ljbHBucmhzanVxdnNnaHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTA0NTIsImV4cCI6MjA2NTEyNjQ1Mn0.hJFI9aMF5ojsIPt9EuIpeKxE0GxX-tVAyEfHyVeFIFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);